### ISSUE TITLE
Mount, Play, UnMount, Mount, Play causes error

### ISSUE THREAD

**Issue by AdmiralPotato** [AdmiralPotato/vue-perfectlooper#5]
Steps to reproduce:
- Visit http://video.nuclearpixel.com/video/metal_eyes-24/
- Play, and let the animation complete loading/scaling
- Navigate back to the videos page
- Navigate back to http://video.nuclearpixel.com/video/metal_eyes-24/
- Try to play

Error details:
```DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at o.updateUI (http://video.nuclearpixel.com/_nuxt/0.nuxt.bundle.1eef4b5580c2d649fb8f.js:1:19308)
    at http://video.nuclearpixel.com/_nuxt/0.nuxt.bundle.1eef4b5580c2d649fb8f.js:1:20208
    at Array.forEach (<anonymous>)
    at s.updateCanvasLoopers (http://video.nuclearpixel.com/_nuxt/0.nuxt.bundle.1eef4b5580c2d649fb8f.js:1:20186)
    at s.addCanvasLooper (http://video.nuclearpixel.com/_nuxt/0.nuxt.bundle.1eef4b5580c2d649fb8f.js:1:20048)
    at new o (http://video.nuclearpixel.com/_nuxt/0.nuxt.bundle.1eef4b5580c2d649fb8f.js:1:16803)
    at a.makeLooper (http://video.nuclearpixel.com/_nuxt/0.nuxt.bundle.1eef4b5580c2d649fb8f.js:1:14416)
    at a.n [as makeLooper] (http://video.nuclearpixel.com/_nuxt/vendor.bundle.9a6a9f45ac29b4eb4040.js:6:1053)
    at a.mounted (http://video.nuclearpixel.com/_nuxt/0.nuxt.bundle.1eef4b5580c2d649fb8f.js:1:12101)
    at jt (http://video.nuclearpixel.com/_nuxt/vendor.bundle.9a6a9f45ac29b4eb4040.js:6:10945)```

**Comment by AdmiralPotato** [comment]
Looks like this was already fixed in 832e9f415eb9b71815b5ddade365cb0d369f5fe4, just needs to be built and added to the next release.
